// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://itltvvidnakrtmovzgvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml0bHR2dmlkbmFrcnRtb3Z6Z3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzAzNzcsImV4cCI6MjA2OTY0NjM3N30.TS-moUgmsr-Yq8auSfIhFUeQaGSdJ6MK1UEvbO7rDfU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});